# Change these first
owner: FearedFusionX # Your GitHub organization or username, where this repository lives
repo: Ro-Status # The name of this repository

sites:
  - name: Roblox Site
    url: https://www.roblox.com
    maxResponseTime: 1000

  - name: Roblox Devforum
    url: https://devforum.roblox.com
    maxResponseTime: 1000

  - name: Roblox Devhub
    url: https://developer.roblox.com
    maxResponseTime: 1000

  - name: Account Information API
    url: https://accountinformation.roblox.com
    method: GET
    maxResponseTime: 1000

  - name: Account Settings API
    url: https://accountsettings.roblox.com
    method: GET
    maxResponseTime: 1000


  - name: Asset Delivery
    url: https://assetdelivery.roblox.com
    method: GET
    maxResponseTime: 1000

  - name: Avatar API Endpoint
    url: https://avatar.roblox.com/v1/avatar-rules
    method: GET
    maxResponseTime: 1000


  - name: Auth API Endpoint
    url: https://auth.roblox.com
    method: GET
    maxResponseTime: 1000

  - name: Badges API Endpoint
    url: https://badges.roblox.com/v1/badges/2124548403
    method: GET
    maxResponseTime: 1000

  - name: Billing API Endpoint

    url: https://billing.roblox.com
    method: GET
    maxResponseTime: 1000    

  - name: CDN API Endpoint
    url: http://cdnproviders.roblox.com/
    method: GET
    maxResponseTime: 1000   

  - name: Catalog API Endpoint
    url: https://catalog.roblox.com/v1/bundles/details?bundleIds=192
    method: GET
    maxResponseTime: 1000

  - name: Datastore API Endpoint
    url: https://gamepersistence.roblox.com/
    method: GET
    maxResponseTime: 1000

  - name: Develop API Endpoint
    url: https://develop.roblox.com/v1/toolbox/items?category=Hat&keyword=Hat
    method: GET
    maxResponseTime: 1000


  - name: Economy API Endpoint
    url: https://economy.roblox.com
    method: GET
    maxResponseTime: 1000

# this is a hack OMG
  - name: Friends API Endpoint
    url: https://friends.roblox.com/v1/metadata
    method: GET
    maxResponseTime: 1000

  - name: Game Join API Endpoint
    url: http://gamejoin.roblox.com/
    method: GET
    maxResponseTime: 1000 
    
  - name: Games API Endpoint
    url: https://games.roblox.com
    method: GET
    maxResponseTime: 1000 

  - name: Groups API Endpoint
    url: https://groups.roblox.com/v1/groups/5680533
    method: GET
    maxResponseTime: 1000

  - name: Inventory API Endpoint
    url: https://inventory.roblox.com/v1/users/82738847/assets/collectibles?limit=10&sortOrder=Asc
    method: GET
    maxResponseTime: 1000

  - name: Text Filter API Endpoint
    url: http://textfilter.roblox.com/
    method: GET
    maxResponseTime: 1
    
    # fix when roblox stop oopsie

  - name: Thumbnails API Endpoint
    url: https://thumbnails.roblox.com/v1/assets?assetIds=82738847&format=Png&isCircular=false&size=30x30
    method: GET
    maxResponseTime: 1000

  - name: Users API Endpoint
    url: https://users.roblox.com/
    method: GET
    maxResponseTime: 1000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /Ro-Status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Ro-Status
  publish: true
  hideNavTitle: true
  scripts:
      - src: https://www.googletagmanager.com/gtag/js?id=G-97T3SSH4DV
        async: true
  js: "window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-97T3SSH4DV');"
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /Ro-Status
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
      
      
      
 workflowSchedule:
  responseTime: "*/10 * * * *"
  staticSite: "*/10 * * * *"
  summary: "*/10 * * * *"
  updates: "*/10 * * * *"
  uptime: "*/10 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
