# Change these first
owner: FearedFusionX # Your GitHub organization or username, where this repository lives
repo: Ro-Status # The name of this repository

sites:
  - name: Roblox Site
    url: https://www.roblox.com
    maxResponseTime: 1000

  - name: Roblox Devforum
    url: https://devforum.roblox.com
    maxResponseTime: 1000

  - name: Roblox Devhub
    url: https://developer.roblox.com
    maxResponseTime: 1000

  - name: Account Information API
    url: https://accountinformation.roblox.com
    method: GET
    maxResponseTime: 1000

  - name: Account Settings API
    url: https://accountsettings.roblox.com
    method: GET
    maxResponseTime: 1000


  - name: Asset Delivery
    url: https://assetdelivery.roblox.com
    method: GET
    maxResponseTime: 1000

  - name: Avatar API Endpoint
    url: https://avatar.roblox.com/v1/avatar-rules
    method: GET
    maxResponseTime: 1000


  - name: Auth API Endpoint
    url: https://auth.roblox.com
    method: GET
    maxResponseTime: 1000

  - name: Badges API Endpoint
    url: https://badges.roblox.com/v1/badges/2124548403
    method: GET
    maxResponseTime: 1000

  - name: Billing API Endpoint
    url: https://billing.roblox.com
    method: GET
    maxResponseTime: 1000    

  - name: Catalog API Endpoint
    url: https://catalog.roblox.com/v1/bundles/details?bundleIds=192
    method: GET
    maxResponseTime: 1000

  - name: Datastore API Endpoint
    url: https://gamepersistence.roblox.com/
    method: GET
    maxResponseTime: 1000

  - name: Develop API Endpoint
    url: http://develop.roblox.com/
    method: GET
    maxResponseTime: 1000


  - name: Economy API Endpoint
    url: https://economy.roblox.com
    method: GET
    maxResponseTime: 1000

# this is a hack OMG
  - name: Friends API Endpoint
    url: https://friends.roblox.com/v1/metadata
    method: GET
    maxResponseTime: 1000
    
  - name: Presence API
    url: https://presence.roblox.com
    method: GET
    maxResponseTime: 1000

  - name: Game Join API Endpoint
    url: http://gamejoin.roblox.com/
    method: GET
    maxResponseTime: 1000 
    
  - name: Games API Endpoint
    url: https://games.roblox.com
    method: GET
    maxResponseTime: 1000 

  - name: Groups API Endpoint
    url: https://groups.roblox.com/v1/groups/5680533
    method: GET
    maxResponseTime: 1000

  - name: Inventory API Endpoint
    url: https://inventory.roblox.com/v1/users/82738847/assets/collectibles?limit=10&sortOrder=Asc
    method: GET
    maxResponseTime: 1000
    
    # fix when roblox stop oopsie

  - name: Thumbnails API Endpoint
    url: https://thumbnails.roblox.com/v1/assets?assetIds=82738847&format=Png&isCircular=false&size=30x30
    method: GET
    maxResponseTime: 1000

  - name: Users API Endpoint
    url: https://users.roblox.com/
    method: GET
    maxResponseTime: 1000
    
  - name: Voice Chat API
    url: https://voice.roblox.com/
    method: GET
    maxResponseTime: 1000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /Ro-Status
  logoUrl: https://raw.githubusercontent.com/FearedFusionX/Ro-Status/master/assets/Full-Logo.svg
  faviconSvg: https://raw.githubusercontent.com/FearedFusionX/Ro-Status/master/assets/upptime-icon.svg
  name: Ro-Status
  publish: true
  hideNavTitle: true
  scripts:
      - src: https://www.googletagmanager.com/gtag/js?id=G-97T3SSH4DV
        async: true
  js: "window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-97T3SSH4DV');"
  navbar:
    - title: Status
      href: /Ro-Status
    - title: GitHub
      href: https://fearedfusionx.github.io/Ro-Status
  introTitle: "**Ro-Status** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is not the offical Roblox Status nor the offical Status + Page. Our status page uses **real-time** data from the Upptime [GitHub repository](https://github.com/upptime/upptime). The Status Page can be used with BDFD.
  css:   "
   
   :root { --body-background-color: #f0f7f7; --body-text-color: #002626; --card-background-color: #ffffff; --nav-background-color: #ffffff; --nav-border-bottom-color: #d8e8e4; --nav-border-bottom-color: #d8e8e4; --nav-current-border-bottom-color: #1abc9c; --card-border-color: #d8e8e4; --down-border-left-color: #eb3b5a; --down-background-color: #750107; --degraded-border-left-color: #f7b731; --up-border-left-color: #20bf6b; --tag-color: #ffffff; --tag-up-background-color: #20bf6b; --tag-down-background-color: #eb3b5a; --tag-degraded-background-color: #f7b731; --change-background-color: #f7b731; --error-button-border-color: #1a46ad; --error-button-background-color: #3867d6; --error-button-color: #ffffff; --submit-button-border-color: #1a46ad; --submit-button-background-color: #3867d6; --submit-button-color: #ffffff; --graph-opacity: 1; --graph-filter: invert(44%) sepia(93%) saturate(2391%) hue-rotate(178deg) brightness(103%) contrast(106%)}
    .svelte-a08hsz { background-color: #111111; color: white; }
    article { border: 1px solid #101010; padding: 1rem 1.25rem; position: relative; border-radius: 0; background-color: #222222; }
    article.good.svelte-1uadwzk { background-color: green; color: white; }    
    chartjs-render-monitor { filter: invert(44%) sepia(93%) saturate(2391%) hue-rotate(178deg) brightness(103%) contrast(106%); }
    body { background-color: #222222; color: white; }
    article { background-color: #111111; }
    nav.svelte-1pyc7i4.svelte-1pyc7i4, nav.svelte-1sgaob0.svelte-1sgaob0 { background: #222222; border-bottom: 1px solid silver; }
    .tag { border-radius: 0; }
    .tag.closed, .tag.up { background-color: green; }
    .chartjs-render-monitor { animation: chartjs-render-animation 0.001s; filter: invert(44%) sepia(93%) saturate(2391%) hue-rotate(0deg) brightness(103%) contrast(106%); }
    "

    
workflowSchedule:
  responseTime: "*/10 * * * *"
  staticSite: "*/10 * * * *"
  summary: "*/10 * * * *"
  updates: "*/10 * * * *"
  uptime: "*/10 * * * *"

i18n:
  footer: Repository from [Ro-Status](https://github.com/FearedFusionX/Ro-Status), 🔌  Maintained by [Upptime.](https://github.com/upptime/upptime)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
